name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.9
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format lib/ --set-exit-if-changed

      - name: Analyze project source
        run: dart analyze